export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const OPEN_POPUP = 'OPEN_POPUP';
export const CLOSE_POPUP = 'CLOSE_POPUP';
export const TOGGLE_REPORTER_INFO = 'TOGGLE_REPORTER_INFO';
export const GET_SUBJECTS = 'GET_SUBJECTS';
export const MARK_REPORTS_OUTDATED = 'MARK_REPORTS_OUTDATED';
export const UPDATE_POPUP_DATA = 'UPDATE_POPUP_DATA';
